import test from "node:test";
import assert from "node:assert/strict";
import { buildValidatedState, buildOfflineSamples, chronologicalSplit, auditOfflineDataset, trainCentroidClassifier, predictCentroid, classificationMetrics, buildOfflineModelSnapshot, evaluateOfflineGate, EXPERT_LABELS, RL_ACTIONS } from "../lib/rl-research/trainer/offline-learning.mjs";

const bars = Array.from({ length: 8 }, (_, i) => ({ symbol: "601899.SH", timestamp: `2022-01-0${i + 1}T09:30:00`, open: 10 + i, high: 10.2 + i, low: 9.8 + i, close: 10 + i, volume: 100 + i, amount: 1000 + i }));
const signals = bars.map((_, i) => ({ action: i % 3 === 0 ? "BUY_SMALL" : i % 3 === 1 ? "SELL_ALL" : "WAIT", marketRegime: "UP", sentimentState: "NEUTRAL", score: 50, strategyId: "OHLCV_T_RESEARCH_V1" }));

test("validated state schema is causal and serializable", () => { const s = buildValidatedState(bars[3], 3, bars, { marketRegime: "UP" }); for (const k of ["return1", "return3", "MA5", "volumeRatio", "marketRegime", "sentimentState", "minuteOfDay", "positionRatio"]) assert.ok(Object.hasOwn(s, k)); assert.doesNotThrow(() => JSON.stringify(s)); });
test("expert labels remain three-class while RL space remains five-class", () => { const ds = buildOfflineSamples(bars, signals); assert.deepEqual([...new Set(ds.map(x => x.expertAction))].sort(), [...EXPERT_LABELS].sort()); assert.deepEqual(RL_ACTIONS, ["WAIT", "BUY_SMALL", "BUY", "SELL_PART", "SELL_ALL"]); });
test("chronological split never uses random assignment", () => { const ds = buildOfflineSamples(bars, signals); const sp = chronologicalSplit(ds); assert.equal(sp.train.length, 5); assert.equal(sp.validation.length, 0); assert.equal(sp.test.length, 0); assert.equal(sp.excluded.length, 3); });
test("dataset audit reports counts, distributions, and integrity checks", () => { const ds = buildOfflineSamples(bars, signals); const report = auditOfflineDataset({ bars, samples: ds, datasetVersion: "data-07", symbol: "601899.SH" }); assert.equal(report.totalBars, 8); assert.equal(report.totalSamples, 8); assert.equal(report.checks.duplicateSampleCount, 0); assert.equal(report.checks.noNaNInfinity, true); assert.equal(report.ranges.train.actionDistribution.BUY_SMALL.count, 2); });
test("centroid model is reproducible and deterministic", () => { const ds = buildOfflineSamples(bars, signals); const a = trainCentroidClassifier(ds); const b = trainCentroidClassifier(ds); assert.deepEqual(a, b); assert.equal(predictCentroid(a, ds[0]), predictCentroid(b, ds[0])); const m = classificationMetrics(ds, a); assert.equal(m.sampleCount, ds.length); assert.ok(Number.isFinite(m.macroF1)); });
test("snapshot and promotion gate preserve production isolation", () => { const model = trainCentroidClassifier(buildOfflineSamples(bars, signals)); const snapshot = buildOfflineModelSnapshot({ datasetHash: "abc", model, trainRange: ["a", "b"], validationRange: ["c", "d"], testRange: ["e", "f"], metrics: { macroF1: 0.5, sellAllRecall: 1 } }); assert.equal(snapshot.affectsSmartT, false); assert.equal(snapshot.canPromoteAutomatically, false); assert.equal(evaluateOfflineGate({ dataset: [1], metrics: { macroF1: 0.5, sellAllRecall: 1 }, snapshot, leakage: "PASS", reproducibility: "PASS", replay: "PASS", datasetUnchanged: true, testUntouched: true, baselinesComplete: true }).OFFLINE_MODEL_READY, "PASS"); });
