import assert from "node:assert/strict";
import test from "node:test";
import { SUPPORTED_ACTIONS, UNSUPPORTED_ACTIONS, createPolicyAccumulator, addPolicySample, fitPolicyModel, predictPolicy, maskProbabilities, buildFeasibilityMask, createClassificationAccumulator, addClassification, finishClassification, hashPolicy, policySchema, walkForwardWindows } from "../lib/rl-research/dataset/policy-research-v012.mjs";

const record = (action = "WAIT", accountState = { cash: 10000, position: 0, sellablePosition: 0, averageCost: null, todayBought: 0 }) => ({ action, state: { marketState: { price: 10, features: { return_1m: 0.01, return_5m: 0.02, price_vs_session_vwap: 0.01, rolling_return_std_20: 0.001, volume_ratio_20: 1, minutesSinceOpen: 10 } }, accountState } });

test("supported action mask excludes BUY and SELL_PART", () => { assert.deepEqual(SUPPORTED_ACTIONS, ["WAIT", "BUY_SMALL", "SELL_ALL"]); assert.deepEqual(UNSUPPORTED_ACTIONS, ["BUY", "SELL_PART"]); const probabilities = maskProbabilities([0.2, 0.3, 0.5], { WAIT: true, BUY_SMALL: false, SELL_ALL: true }); assert.ok(Math.abs(probabilities[0] - 2 / 7) < 1e-12); assert.equal(probabilities[1], 0); assert.ok(Math.abs(probabilities[2] - 5 / 7) < 1e-12); });
test("policy training and prediction are deterministic with probabilities summing to one", () => { const a = createPolicyAccumulator("market_account"); for (const action of ["WAIT", "BUY_SMALL", "SELL_ALL", "WAIT"]) addPolicySample(a, record(action)); const model = fitPolicyModel(a); const prediction = predictPolicy(model, record()); assert.equal(Object.values(prediction.probabilities).reduce((x, y) => x + y, 0), 1); assert.deepEqual(model, fitPolicyModel(a)); assert.equal(hashPolicy(model), hashPolicy(model)); });
test("SELL_ALL is masked without sellable inventory", () => { const a = createPolicyAccumulator(); addPolicySample(a, record("WAIT")); addPolicySample(a, record("SELL_ALL", { cash: 10000, position: 100, sellablePosition: 100, averageCost: 10, todayBought: 0 })); const prediction = predictPolicy(fitPolicyModel(a), record("WAIT")); assert.equal(buildFeasibilityMask(prediction ? record() : record()).SELL_ALL, false); assert.equal(prediction.probabilities.SELL_ALL, 0); });
test("classification metrics expose WAIT dominance and rare action support", () => { const acc = createClassificationAccumulator(); for (const action of ["WAIT", "WAIT", "BUY_SMALL", "SELL_ALL"]) addClassification(acc, action, { action, probabilities: { WAIT: action === "WAIT" ? 1 : 0, BUY_SMALL: action === "BUY_SMALL" ? 1 : 0, SELL_ALL: action === "SELL_ALL" ? 1 : 0 }, confidence: 1, feasibilityMask: { WAIT: true, BUY_SMALL: true, SELL_ALL: action !== "WAIT" }, ood: false }); const result = finishClassification(acc); assert.equal(result.perAction.SELL_ALL.support, 1); assert.equal(result.nonWaitAccuracy, 1); });
test("temporal windows and schema are explicit and causal", () => { assert.equal(walkForwardWindows().length, 3); const schema = policySchema({ datasetHash: "d", sourceTrajectoryHash: "t", sourceDatasetHash: "s", normalizedDatasetHash: "n", expertSignalHash: "e" }); assert.equal(schema.nextStateInInput, false); assert.equal(schema.futureRewardInInput, false); });
