import assert from "node:assert/strict";
import test from "node:test";
import { PerformanceAnalyticsEngine, checkSampleIntegrity } from "../lib/paper-trading/index.mjs";

const sample = (overrides = {}) => ({ timestamp: "2026-09-30T10:00", entryPrice: 10, signal: "BUY", signalScore: 82, candidateId: "c1", factorSnapshot: { vwap: 9.9 }, marketState: "trend", modelVersion: "m1", datasetVersion: "d1", pnl: 0.01, holdingTime: 5, ...overrides });
test("performance calculates core metrics and risk", () => { const report = new PerformanceAnalyticsEngine().analyze([sample(), sample({ pnl: -0.02 }), sample({ pnl: 0.03 })]); assert.equal(report.summary.totalSamples, 3); assert.equal(report.summary.totalTrades, 3); assert.equal(report.summary.wins, 2); assert.equal(report.summary.losses, 1); assert.ok(report.summary.profitFactor > 1); assert.equal(report.risk.maximumConsecutiveWin, 1); });
test("performance groups by candidate, score, factor and market", () => { const report = new PerformanceAnalyticsEngine().analyze([sample(), sample({ candidateId: "c2", signalScore: 65, factorSnapshot: { macd: 1 }, marketState: "range" })]); assert.ok(report.breakdown.candidateId.c1); assert.ok(report.breakdown.signalScore["60-69"]); assert.ok(report.breakdown.factorId.macd); assert.ok(report.breakdown.marketState.range); });
test("return distribution separates large and small outcomes", () => { const report = new PerformanceAnalyticsEngine().analyze([sample({ pnl: 0.03 }), sample({ pnl: 0.01 }), sample({ pnl: -0.01 }), sample({ pnl: -0.03 })]); assert.deepEqual(report.returnDistribution, { largeProfit: 1, smallProfit: 1, smallLoss: 1, largeLoss: 1 }); });
test("invalid samples are excluded and reported", () => { const invalid = sample({ timestamp: "", entryPrice: null, factorSnapshot: null, candidateId: "", pnl: null, future1mReturn: null }); assert.equal(checkSampleIntegrity(invalid).valid, false); const report = new PerformanceAnalyticsEngine().analyze([sample(), invalid]); assert.equal(report.sampleQuality.invalid, 1); assert.equal(report.summary.totalSamples, 1); });
