import assert from "node:assert/strict";
import test from "node:test";
import { TradingDecisionEngine } from "../lib/paper-trading/index.mjs";

const engine = new TradingDecisionEngine();
test("same input produces the same decision", () => { const input = { marketRegime: { trend: "UP" }, sentimentState: { panicRelease: true }, factorSnapshot: { buyPressure: 2, sellPressure: 1 }, positionState: { canBuy: true }, historicalPerformance: { winRate: .6 } }; assert.deepEqual(engine.decide(input), engine.decide(input)); });
test("rules produce BUY SELL_PART SELL and RANGE HOLD", () => { assert.equal(engine.decide({ marketRegime: { trend: "UP" }, sentimentState: { panicRelease: true }, factorSnapshot: { buyPressure: 2, sellPressure: 1 } }).decision, "BUY"); assert.equal(engine.decide({ marketRegime: { trend: "UP" }, sentimentState: { rapidRise: true, stalling: true }, factorSnapshot: { buyPressure: 1, sellPressure: 2 } }).decision, "SELL_PART"); assert.equal(engine.decide({ marketRegime: { trend: "DOWN" }, sentimentState: { reboundLowVolume: true } }).decision, "SELL"); assert.equal(engine.decide({ marketRegime: { trend: "SIDEWAYS" } }).decision, "HOLD"); });
test("decision reason is complete and confidence is bounded", () => { const result = engine.decide({ marketRegime: { trend: "UP" }, sentimentState: { panicRelease: true }, factorSnapshot: { buyPressure: 1, sellPressure: 0 } }); assert.ok(result.reason.length > 0); assert.ok(result.confidence >= 0 && result.confidence <= 1); assert.equal(result.canAutoTrade, false); });
test("historical sample context can be passed without side effects", () => { const sample = { marketRegime: "UP", factorSnapshot: { buyPressure: 3, sellPressure: 1 }, candidateId: "c1", modelVersion: "m1" }; const result = engine.decide({ marketRegime: { trend: sample.marketRegime }, factorSnapshot: sample.factorSnapshot, positionState: { canBuy: true } }); assert.equal(result.decision, "WAIT"); assert.equal(sample.candidateId, "c1"); });
