export type SmartTMinute = { time: string; price: number; volume: number };
export type SmartTAction = {
  time: string;
  side: "买入" | "卖出";
  price: number;
  quantity: number;
  curveIndex: number;
  direction: "正T" | "反T";
  cycleId: number;
  reason: string;
  meta?: Record<string, number | string | boolean>;
};
export type SmartTObservation = {
  time: string;
  price: number;
  direction: "正T" | "反T";
  score: number;
  threshold: number;
  edge: number;
  executable: boolean;
  stage: "watch" | "candidate";
  pairGap: number | null;
  pivotTime: string;
  pivotPrice: number;
  pivotLabel: string;
  pivotAssessment: "strong" | "confirmed" | "unconfirmed";
  confirmationLabel: string;
  blockers: string[];
  reason: string;
};
export type SmartTReplayResult = {
  net: number;
  gross: number;
  fees: number;
  executionCost: number;
  maxDrawdown: number;
  trades: number;
  wins: number;
  days: number;
  curve: number[];
  curveTimes: string[];
  cycleNets: number[];
  startTime: string;
  status: string;
  actions: SmartTAction[];
  observations: SmartTObservation[];
  diagnostics: Record<string, number>;
};
export type SmartTOptions = {
  capital: number;
  baseShares: number;
  sellable: number;
  feeRate: number;
  slippage: number;
  minCommission: boolean;
  slippageMode: "percent" | "tick";
  forceCloseTime: string;
  profile?: string;
  profileOverrides?: Record<string, number>;
  previousClose?: number | null;
  randomValue?: number;
};
export function runSmartTReplay(minutes: SmartTMinute[], options: SmartTOptions): SmartTReplayResult;
export const PROFILES: Record<string, {
  score: number;
  cooldown: number;
  candidateNetPct: number;
  targetNetPct: number;
  maxTargetNetPct: number;
  minHoldMinutes: number;
  maxCycles: number;
  deviation: number;
  reversal: number;
  maxSellPullback: number;
  hardStopPct?: number;
  softStopPct?: number;
  softStopMinutes?: number;
  timeExitMinutes?: number;
  trailActivationPct?: number;
  trailRetracePct?: number;
  trailMinNetPct?: number;
  maxOpeningChasePct?: number;
  strongBuySessionMove?: number;
  strongBuyVwap30?: number;
  strongSellSessionMove?: number;
  strongSellVwap30?: number;
  counterTrendVwap30?: number;
  counterTrendSessionMove?: number;
  counterTrendMinVolumeRatio?: number;
}>;
